// <auto-generated />
using System;
using BookingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingAPI.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingAPI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingAPI.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("HasKitchen")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWashingMachine")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<int>("PricePerNight")
                        .HasColumnType("int");

                    b.Property<int>("Sqm")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Moo 2, Chaweng Beach",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "Koh Samui",
                            Country = "Thailand",
                            Description = "Cozy wooden bungalow just 50 meters from the turquoise waters of Koh Samui. Ideal for couples looking for a peaceful escape.",
                            HasAirConditioning = true,
                            HasKitchen = false,
                            HasParking = true,
                            HasWashingMachine = false,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1717119125410-29c3edf6e075?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
                            MaxGuests = 2,
                            PricePerNight = 85,
                            Sqm = 35,
                            Title = "Seaside Bungalow"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 Sunset Road",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            City = "Phuket",
                            Country = "Thailand",
                            Description = "Spacious luxury villa on Phuket's west coast with private pool and panoramic ocean view. Perfect for families or groups.",
                            HasAirConditioning = true,
                            HasKitchen = true,
                            HasParking = true,
                            HasWashingMachine = true,
                            HasWifi = true,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1682377521697-bc598b52b08a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1215",
                            MaxGuests = 6,
                            PricePerNight = 290,
                            Sqm = 180,
                            Title = "Luxury Villa with Ocean View"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Haad Yuan Bay",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "Koh Phangan",
                            Country = "Thailand",
                            Description = "Rustic bamboo hut located right on the beach of Koh Phangan. Simple but magical experience for nature lovers.",
                            HasAirConditioning = false,
                            HasKitchen = false,
                            HasParking = false,
                            HasWashingMachine = false,
                            HasWifi = false,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1687960116228-13d383d20188?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
                            MaxGuests = 2,
                            PricePerNight = 50,
                            Sqm = 28,
                            Title = "Beachfront Bamboo Hut"
                        },
                        new
                        {
                            Id = 4,
                            Address = "89/7 Beach Avenue",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "Phuket",
                            Country = "Thailand",
                            Description = "Modern and stylish condo just 5 minutes walk from Patong Beach. Includes pool access and gym.",
                            HasAirConditioning = true,
                            HasKitchen = true,
                            HasParking = true,
                            HasWashingMachine = false,
                            HasWifi = true,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1687960117069-567a456fe5f3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
                            MaxGuests = 3,
                            PricePerNight = 110,
                            Sqm = 60,
                            Title = "Modern Condo near Patong Beach"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Soi Ao Nang 6",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "Krabi",
                            Country = "Thailand",
                            Description = "Charming villa surrounded by lush tropical gardens in Krabi. 10-minute walk to Ao Nang beach. Great for families with kids.",
                            HasAirConditioning = true,
                            HasKitchen = true,
                            HasParking = true,
                            HasWashingMachine = true,
                            HasWifi = true,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1675745329378-5573c360f69f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170",
                            MaxGuests = 4,
                            PricePerNight = 160,
                            Sqm = 95,
                            Title = "Tropical Garden Villa"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ocean Cliff Road",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "Koh Tao",
                            Country = "Thailand",
                            Description = "Exclusive villa perched on a cliff in Koh Tao with private infinity pool and breathtaking sunset views.",
                            HasAirConditioning = true,
                            HasKitchen = true,
                            HasParking = true,
                            HasWashingMachine = true,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1728050829093-9ee62013968a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1171",
                            MaxGuests = 5,
                            PricePerNight = 320,
                            Sqm = 140,
                            Title = "Cliffside Pool Villa"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Beachside Lane 5",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "Hua Hin",
                            Country = "Thailand",
                            Description = "Bright minimalist-style studio located in Hua Hin, 200 meters from the beach. Great for remote work and relaxation.",
                            HasAirConditioning = true,
                            HasKitchen = true,
                            HasParking = true,
                            HasWashingMachine = false,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1543489822-c49534f3271f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1332",
                            MaxGuests = 2,
                            PricePerNight = 70,
                            Sqm = 40,
                            Title = "Minimalist Studio near the Sea"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ban Pak Meng",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            City = "Trang",
                            Country = "Thailand",
                            Description = "Authentic Thai teakwood house in Chiang Mai style, relocated to a quiet seaside village near Trang. A cultural and peaceful stay.",
                            HasAirConditioning = false,
                            HasKitchen = true,
                            HasParking = true,
                            HasWashingMachine = false,
                            HasWifi = true,
                            ImageUrl = "https://images.unsplash.com/photo-1692736933760-8a8a9b8c1b6f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1074",
                            MaxGuests = 4,
                            PricePerNight = 95,
                            Sqm = 85,
                            Title = "Traditional Thai House"
                        });
                });

            modelBuilder.Entity("BookingAPI.Models.Booking", b =>
                {
                    b.HasOne("BookingAPI.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });
#pragma warning restore 612, 618
        }
    }
}
